appuio/appuio-cloud-reporting

- pkg/db/util.go
- pkg/db/util_test.go
- pkg/report/options.go
- pkg/report/report.go
- pkg/report/report_test.go
- report_command.go
* Adds a progress reporter
* Passes cancellation signals
* Allows Prometheus queries to timeout
> QoL Improvements: Cancellation, Progress reporter, Prom timeout

- Makefile
- Makefile.compose.mk
- Makefile.vars.mk
- README.md
- docker-compose-test.yml
- docker-compose.yml
* Adds docker-compose for easy test setup
* Requires that developers have `docker-compose` or Docker compose v2
> Add docker compose setup for local testing

- pkg/db/seeds/appuio_cloud_persistent_storage.promql
Now that we have a second zone, the query fails due to labels not being
unique on a many-to-many time series join. Also join on `cluster_id`
resolves this.
> Fix PromQL join on persistent storage

- pkg/invoice/invoice.go
- pkg/invoice/invoice_test.go
The database IDs are internal and should never be exposed. Also exposing the IDs in invoices makes testing needlessly complicated, as the ID changes with every run.
Very strictly speaking this is a breaking change, but I seriously hope we never used this ID
> Do not expose DB IDs in the invoice

- go.mod
- go.sum
- pkg/db/seeds.go
- pkg/db/seeds/appuio_cloud_memory_sub_cpu.promql
- pkg/db/seeds/appuio_cloud_memory_sub_memory.promql
- pkg/db/seeds_test.go
- pkg/db/types.go
Add default sub queries to seed. Tried not to be too smart with seeding as it quickly get's confusing. We only add the sub queries if we also add the main query.
The main query update is done in https://github.com/appuio/appuio-cloud-reporting/pull/46
> Add subqueries for memory query

- pkg/invoice/invoice.go
- pkg/invoice/invoice_test.go
- pkg/invoice/testdata/discounts.json
- pkg/invoice/testdata/products.json
- pkg/invoice/testdata/simple.json
- pkg/invoice/testdata/timed_discounts.json
- pkg/invoice/testdata/timed_query.json
By returning the query names for line items, ERP adapters can detect the source of a line item and handle the invoice rendering accordingly. This can for example be helpful for sub-items.
We may or may not need this for the Odoo adapter, but I don't see a reason to hide this information
> Expose the query name for every invoice line item

- pkg/invoice/invoice.go
- pkg/invoice/invoice_test.go
- pkg/invoice/main_test.go
- pkg/invoice/testdata/discounts.json
- pkg/invoice/testdata/products.json
- pkg/invoice/testdata/simple.json
- pkg/invoice/testdata/timed_discounts.json
- pkg/invoice/testdata/timed_query.json
In https://github.com/appuio/appuio-cloud-reporting/pull/65 it was suggested to switch to a map for subitems in invoices.
This is technically a breaking change, but as we did not have a release since introducing subitems we can ignore this
> Return subitems in invoices as a map

- pkg/db/seeds/appuio_cloud_memory.promql
- pkg/db/seeds/appuio_cloud_memory_sub_cpu.promql
- pkg/db/seeds/appuio_cloud_memory_sub_memory.promql
Right now we also count requests for terminated pods. We should not do
this.
This query will take effect on 2022-05-06 00:00:00
> Only count CPU and memory requests of running pods

- pkg/db/seeds/appuio_cloud_memory.promql
- pkg/db/seeds/appuio_cloud_memory_sub_cpu.promql
- pkg/db/seeds/appuio_cloud_memory_sub_memory.promql
When force-replacing a pod, two pods with the same name, but differing `uid` label, can exist for a short time in the time series.
> Fix query error caused by force-replaced pod

- pkg/thanos/thanos.go
- pkg/thanos/thanos_test.go
- report_command.go
We got missing data and did not see it. The default is just returning data that can be queried.
https://thanos.io/v0.28/components/query.md/#partial-response-strategy
> Abort request if data is missing (not all Thanos stores are available)

- pkg/db/seeds/appuio_cloud_memory.promql
- pkg/db/seeds/appuio_cloud_memory_sub_cpu.promql
- pkg/db/seeds/appuio_cloud_memory_sub_memory.promql
- pkg/sourcekey/sourcekey_test.go
In the end every user schedulable node should have label:
```yaml
appuio.io/node-class: general-purpose
appuio.io/node-class: gpu
appuio.io/node-class: plus
appuio.io/node-class: flex
```
Testing with `kubernetes.io/arch` (all labels same value) and `kubernetes.io/hostname`.
Performance takes a hit. Average query goes from ~11 seconds to ~20. Does not really matter to where the node label is moved.
> Add node label as class for compute queries

- pkg/db/seeds/appuio_cloud_memory.promql
- pkg/db/seeds/appuio_cloud_memory_sub_cpu.promql
- pkg/db/seeds/appuio_cloud_memory_sub_memory.promql
Prometheus keeps series "alive" for 5 minutes after they get dropped from a scrape target. This leads to a slight overlap in the `kube_node_labels` metric if a node is relabelled.
This commit prioritises series having a node class label over series without.
This still does not work if a node class label changes from non-empty to non-empty but that should never happen. I don't think there is a generic way to handle this case.
Tested with LPG2 data at `2022-11-11 10:00:00Z`.
> Fix queries if node class label is added

- pkg/db/seeds/appuio_cloud_persistent_storage.promql
- pkg/db/seeds/promtest/appuio_cloud_persistent_storage.jsonnet
Info label changes can happen on CSI driver updates. Seen on LPG2 after maintenance.
Fixes https://github.com/appuio/appuio-cloud-reporting/issues/104#issuecomment-1339446982.
> Fix query on PV info change

- pkg/db/seeds/appuio_cloud_loadbalancer.promql
- pkg/db/seeds/appuio_cloud_memory.promql
- pkg/db/seeds/appuio_cloud_persistent_storage.promql
- pkg/db/seeds/promtest/appuio_cloud_loadbalancer.jsonnet
- pkg/db/seeds/promtest/appuio_cloud_memory.jsonnet
- pkg/db/seeds/promtest/appuio_cloud_persistent_storage.jsonnet
- pkg/db/seeds/promtest/common.libsonnet
Changes to namespace labels and organization changes can lead to many-to-many matching errors
```
bottomk(1,
min by (cluster_id, namespace, tenant_id) (
_INFO_SERIES
)
) by(cluster_id, namespace)
```
Chooses a random `tenant_id` for every point if there is an overlap.
> Fix query on namespace label changes and organization change

- pkg/db/seeds/appuio_cloud_memory.promql
- pkg/db/seeds/appuio_cloud_memory_sub_cpu.promql
- pkg/db/seeds/appuio_cloud_memory_sub_memory.promql
Follow up of #112. Forgot to implement the fix for subqueries too.
> Add namespace label fix to subqueries too

- pkg/db/seeds.go
- pkg/db/seeds/appcat_postgresql_vshn_standalone.promql
- pkg/db/seeds_test.go
This PR adds a query so that we can bill VSHN managed PostgreSQL on APPUiO Cloud-
> Add billing query for VSHN PostgreSQL standalone

- pkg/thanos/thanos.go
- pkg/thanos/thanos_test.go
- report_command.go
- tenantmapping_command.go
This header is required when querying a Mimir instance. It can be set via command line or environment variable.
Currently only this specific header can be set by the user.
Relates to OCP-620
> Add a command line option to set the X-Scope-OrgID header in Prometheus requests

- check_command.go
- pkg/check/inconsistent.go
- pkg/check/inconsistent_test.go
- pkg/db/migrations/0014_enforce_date_times_timestamp_consistency.sql
- pkg/db/types.go
- pkg/db/util.go
- pkg/tenantmapping/mapping_test.go
Dimension time ranges can be update after a fact was created which can lead to inconsistent data where the fact timestamp is not in the range of the dimension time range.
This already happened when we introduced the `flex`/`plus` nodes. And will now happen again with the automatic tenant updates.
> Add check for facts with inconsistent fact/dimension time ranges.

- pkg/db/seeds.go
- pkg/db/seeds/appuio_managed_kubernetes_vcpu.promql
- pkg/db/seeds/promtest/appuio_managed_kubernetes_vcpu.jsonnet
- pkg/db/seeds/promtest/appuio_managed_openshift_vcpu.jsonnet
- pkg/db/seeds_test.go
* Add vCPU query for APPUiO Managed Kubernetes
> Add vCPU query for APPUiO Managed Kubernetes

- Makefile
- pkg/db/seeds.go
- pkg/db/seeds/appcat_vshn.promql.tmpl
With the updated  billing model we use different naming for the AppCat queries and also match on a different namespace label. The label switch is done so that both the old and new query continue to work.  See: https://github.com/vshn/component-appcat/pull/144
> Update AppCat VSHN PostgreSQL and VSHN Redis query to new pricing model

- pkg/db/seeds.go
- pkg/db/seeds/appuio_managed_openshift_clusters_legacy.promql
- pkg/db/seeds/appuio_managed_openshift_vcpu.promql
- pkg/db/seeds/promtest/appuio_managed_openshift_clusters_legacy.jsonnet
- pkg/db/seeds/promtest/appuio_managed_openshift_vcpu.jsonnet
- pkg/db/seeds_test.go
This adds/updates the necessary queries for APPUiO Managed OpenShift reporting.
I've realized that we can use the same vCPU query for both the new and the old billing, and distinguish between the two models based on the SLA - the old model uses a disjoint list of SLAs.
In a similar vein, the Cluster query - used for the cluster base fee from the old billing model - is set up to only return values for clusters with one of the old SLAs. In this way, new clusters won't get facts for the cluster count, and therefore won't be billed for that.
~Currently, the queries use a lookup key format of `query:cloud:sla:tenant:cluster[:role]` - this only works if we accept #147. Without #147, the tenant must be at the 3rd position in the lookup key. It could be made to work that way, it would just lead …
> Add queries for APPUiO Managed billing

- pkg/invoice/invoice_golden_test.go
- pkg/report/report.go
- pkg/sourcekey/sourcekey.go
- pkg/sourcekey/sourcekey_test.go
According to the [documentation](https://kb.vshn.ch/appuio-cloud/references/architecture/metering-data-flow.html#_system_idea), the implementation of the dimension lookup process should not make any assumptions about the length of the source key (in number of elements), or the specific meaning of each element.
The implementation currently makes such an assumption, and in particular, the source key is restricted to have either 4 or 5 elements.
In this PR, I remove the maximum length restriction for the source key. The behavior for keys of length 4 or 5 stays the same, so this change should be perfectly backwards compatible.
Also for the sake of backwards compatibility, the association of the first 5 key elements with a specific meaning is kept in the code. The code assumes the key to be of …
> Generalize source key implementation to arbitrary-length keys
